In [28]:
import torch
import numpy as np

In [12]:
N, D = 3, 4
# Define tensors
x = torch.randn(N, D, requires_grad=True)
y = torch.randn(N, D, requires_grad=True)
z = torch.randn(N, D, requires_grad=True)

In [13]:
# Forward computation
a = x * y
b = a + z
c = torch.sum(b)

In [14]:
# Backward propagation
c.backward()

print(x.grad)
print(y.grad)
print(z.grad)

tensor([[ 1.7123,  0.0100,  0.8626, -0.2881],
        [ 1.2074,  0.6320, -2.2519,  0.9246],
        [-0.3916,  0.3038, -1.2201, -1.4378]])
tensor([[-0.5010, -0.7405, -0.6437, -0.2504],
        [ 0.6147,  0.1546,  2.3687,  0.8019],
        [-0.1534, -0.3059,  1.1889, -0.1786]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [16]:
# Similarly as in Numpy, we can create a zero-tensor in PyTorch
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [19]:
# Or we can also create a tensor directly from a list
x = torch.tensor([1, 2, 3])
print(x)
print(x.dtype)

tensor([1, 2, 3])
torch.int64


In [20]:
x = torch.tensor([2.4, 1])
print(x)
print(x.dtype)

tensor([2.4000, 1.0000])
torch.float32


In [22]:
# Get the size of a tensor
print(x.size())
x = torch.ones(4, 5)
print(x.size())

torch.Size([2])
torch.Size([4, 5])


In [24]:
# To reshape the size of a tensor, use .view function
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
# For a scalar tensor, use .item function to get its value
t = torch.randn(1)
print(t)
print(t.item())

tensor([-0.3127])
-0.31267285346984863


In [35]:
# One can also translate between numpy and pytorch seamlessly
a = np.random.rand(4, 4)
b = torch.from_numpy(a)
print(a)
print(b)

[[0.71251956 0.55269068 0.34798382 0.45690354]
 [0.77975698 0.37785224 0.33958764 0.77233541]
 [0.58358928 0.06533935 0.26789369 0.35507593]
 [0.39157167 0.69885708 0.60247685 0.28006096]]
tensor([[0.7125, 0.5527, 0.3480, 0.4569],
        [0.7798, 0.3779, 0.3396, 0.7723],
        [0.5836, 0.0653, 0.2679, 0.3551],
        [0.3916, 0.6989, 0.6025, 0.2801]], dtype=torch.float64)


In [36]:
b = torch.randn(4, 4)
a = b.numpy()
print(a)
print(b)

[[ 1.1762104  -0.7075631   1.0117321   0.3027173 ]
 [-0.38124004  0.5757111   1.5964781  -1.4748666 ]
 [ 0.10169525  1.4607219   0.34397843 -0.5107189 ]
 [ 1.2519964  -0.19499914 -0.810587    0.63314253]]
tensor([[ 1.1762, -0.7076,  1.0117,  0.3027],
        [-0.3812,  0.5757,  1.5965, -1.4749],
        [ 0.1017,  1.4607,  0.3440, -0.5107],
        [ 1.2520, -0.1950, -0.8106,  0.6331]])
